# Generated by Django 4.0.2 on 2022-03-05 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mockedbankaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accounts',
            field=models.ManyToManyField(default=None, null=True, to='core.MockedBankAccount'),
        ),
        migrations.AlterField(
            model_name='mockedtransactions',
            name='transactionDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 5, 4, 59, 5, 611246)),
        ),
    ]
