# Generated by Django 4.0.2 on 2022-03-08 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_mockedtransactions_transactiondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockedtransactions',
            name='transactionDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 7, 23, 42, 44, 918856)),
        ),
    ]
