# Generated by Django 4.0.2 on 2022-03-08 03:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_mockedtransactions_transactiondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockedtransactions',
            name='transactionDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 0, 4, 16, 172853)),
        ),
        migrations.CreateModel(
            name='MockedConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consentId', models.CharField(max_length=64, unique=True)),
                ('creationDateTime', models.DateTimeField(default=datetime.datetime(2022, 3, 8, 0, 4, 16, 219767))),
                ('status', models.CharField(choices=[('AGUARDANDO_AUTORIZACAO', 'Aguardando autorização'), ('AUTORIZADO', 'Autorizado'), ('REVOGADO', 'Revogado')], default='AGUARDANDO_AUTORIZACAO', max_length=255)),
                ('statusUpdateDateTime', models.DateTimeField(default=datetime.datetime(2022, 3, 8, 0, 4, 16, 219767))),
                ('permissions', models.CharField(default='LEITURA_DE_CONTA', max_length=255)),
                ('expirationDateTime', models.DateTimeField(default=datetime.datetime(2022, 5, 8, 0, 4, 16, 219767))),
                ('transactionFromDateTime', models.DateTimeField(default=datetime.datetime(2021, 3, 8, 0, 4, 16, 219767))),
                ('transactionToDateTime', models.DateTimeField(default=datetime.datetime(2022, 5, 8, 0, 4, 16, 219767))),
                ('bankAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mockedbankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
