# Generated by Django 4.0.2 on 2022-03-15 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_mockedconsent_creationdatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockedconsent',
            name='creationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 22, 29, 49, 885306)),
        ),
        migrations.AlterField(
            model_name='mockedconsent',
            name='expirationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 22, 29, 49, 885306)),
        ),
        migrations.AlterField(
            model_name='mockedconsent',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_AUTORIZACAO', 'Aguardando autorização'), ('AUTORIZADO', 'Autorizado'), ('REVOGADO', 'Revogado')], default='AUTORIZADO', max_length=255),
        ),
        migrations.AlterField(
            model_name='mockedconsent',
            name='statusUpdateDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 22, 29, 49, 885306)),
        ),
        migrations.AlterField(
            model_name='mockedconsent',
            name='transactionFromDateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 22, 29, 49, 885306)),
        ),
        migrations.AlterField(
            model_name='mockedconsent',
            name='transactionToDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 22, 29, 49, 885306)),
        ),
        migrations.AlterField(
            model_name='mockedtransactions',
            name='transactionDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 22, 29, 49, 854306)),
        ),
    ]
