# Generated by Django 4.0.2 on 2022-03-16 01:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_mockedconsent_creationdatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockedconsent',
            name='bankAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.mockedbankaccount'),
        ),
        migrations.AlterField(
            model_name='mockedconsent',
            name='creationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 22, 42, 12, 406846)),
        ),
        migrations.AlterField(
            model_name='mockedconsent',
            name='expirationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 22, 42, 12, 406846)),
        ),
        migrations.AlterField(
            model_name='mockedconsent',
            name='statusUpdateDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 22, 42, 12, 406846)),
        ),
        migrations.AlterField(
            model_name='mockedconsent',
            name='transactionFromDateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 22, 42, 12, 406846)),
        ),
        migrations.AlterField(
            model_name='mockedconsent',
            name='transactionToDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 22, 42, 12, 406846)),
        ),
        migrations.AlterField(
            model_name='mockedconsent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mockedtransactions',
            name='transactionDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 22, 42, 12, 328750)),
        ),
    ]
