# Generated by Django 4.0.2 on 2022-03-18 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_category_alter_mockedconsent_creationdatetime_and_more'),
        ('core', '0010_alter_mockedconsent_bankaccount_and_more'),
    ]

    operations = [
    ]
