# Generated by Django 3.2.12 on 2022-03-23 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20220318_1841'),
        ('core', '0011_user_cpf_user_tel_and_more'),
    ]

    operations = [
    ]
