# Generated by Django 3.2.12 on 2022-03-23 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20220323_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='OBPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('ACCOUNTS_READ', 'ACCOUNTS_READ'), ('ACCOUNTS_BALANCES_READ', 'ACCOUNTS_BALANCES_READ'), ('ACCOUNTS_TRANSACTIONS_READ', 'ACCOUNTS_TRANSACTIONS_READ'), ('ACCOUNTS_OVERDRAFT_LIMITS_READ', 'ACCOUNTS_OVERDRAFT_LIMITS_READ')], default='ACCOUNTS_READ', max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='mockedconsent',
            name='creationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 10, 31, 13, 592537)),
        ),
        migrations.AlterField(
            model_name='mockedconsent',
            name='expirationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 10, 31, 13, 592689)),
        ),
        migrations.RemoveField(
            model_name='mockedconsent',
            name='permissions',
        ),
        migrations.AlterField(
            model_name='mockedconsent',
            name='statusUpdateDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 10, 31, 13, 592623)),
        ),
        migrations.AlterField(
            model_name='mockedconsent',
            name='transactionFromDateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 10, 31, 13, 592775)),
        ),
        migrations.AlterField(
            model_name='mockedconsent',
            name='transactionToDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 10, 31, 13, 592838)),
        ),
        migrations.AlterField(
            model_name='mockedtransactions',
            name='transactionDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 10, 31, 13, 581342)),
        ),
        migrations.AddField(
            model_name='mockedconsent',
            name='permissions',
            field=models.ManyToManyField(default=None, null=True, to='core.OBPermissions'),
        ),
    ]
