# Generated by Django 3.2.12 on 2022-03-24 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20220324_1602'),
        ('core', '0013_auto_20220323_1031'),
    ]

    operations = [
    ]
